# ===================================================================
# JHipster Sample Spring Cloud Config.
# ===================================================================

# Property used on app startup to check the config server status
configserver:
    name: JHipster Registry config server
    status: Connected to the JHipster Registry config server, using https://github.com/jhipster/jhipster-registry-sample-config !

# Default JWT secret token (to be changed in production!)
jhipster:
    security:
        authentication:
            jwt:
                secret: MDc5ZGNjMjBmYzM4M2VjOThjOWRlYmFlZWRlZWFmM2I3OTkxZjlhNTIyMGEyMmMwMGZmOTZjNDg0YWY2OTAzMjY1MGI1MzRiYjEwMmIzODNhODk4NmU1NTA4Y2ZkYTc5ZDE5YzBiZjE3YzEwYjM2MTYwNzA2MDc2ZDUzMGQ1N2U=
                
application:
    say: hello
